### PR TITLE
Fix exponentiation parentheses.

### LINKED ISSUE #142: Improper treatment of exponents with negative base
I get

```julia
julia> latexify("(-1)^2")
L"$-1^{2}$"
```

However, `- 1^2 != (-1)^2`.

### PR DESCRIPTION
**Pull request by korsbo**
closes #142

### CODE REVIEW

File: src/latexoperation.jl [hunk 1]
```diff
@@ -67,7 +67,11 @@ function latexoperation(ex::Expr, prevOp::AbstractArray; cdot=true, index=:brack
             str = get(function2latex, prevOp[2], "\\$(prevOp[2])")
             return replace(args[2], str => "$(str)^{$(args[3])}")
         end
-        prevOp[2] != :none  && (args[2]="\\left( $(args[2]) \\right)")
+        # prevOp[2] != :none  && (args[2]="\\left( $(args[2]) \\right)")
+        @show dump(ex)
```
Comment (korsbo) [inline src/latexoperation.jl:71]: Ouch!
